[project]
name = "llmt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prompt-toolkit>=3.0.47",
    "pygments>=2.18.0",
    "pyperclip>=1.9.0",
    "pytest>=8.3.3",
    "requests>=2.32.3",
]
